chore(appeals): upgrading azurerm to version 4
Planning-Inspectorate/appeals-back-office pull request #623
Opened 2024-11-07 13:37 UTC by m-juckes-pins

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2024-11-07 13:54 UTC, m-juckes-pins commented on infrastructure/service-bus.tf
> -  zone_redundant               = var.service_bus_config.sku == "Premium"
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub_namespace

2024-11-07 13:55 UTC, m-juckes-pins commented on infrastructure/service-bus.tf
> -  zone_redundant               = var.service_bus_config.sku == "Premium"
possibly need to look somewhere else in terraform to replace this

2024-11-07 13:56 UTC, m-juckes-pins commented
Created a pre-commit file but only at the infra level so not to affect anything at root level such as line spacing etc

2024-11-07 13:58 UTC, m-juckes-pins commented
- If the provider config in the module is commented out, appeals will pass validation but modules will fail. 
- If the provider block is not commented out appeals will fail validation, but modules will pass, 

``` modules repo
terraform {
  required_providers {
    azurerm = {
      source                = "hashicorp/azurerm"
      version               = ">= 3.0, < 5.0"
      configuration_aliases = [azurerm, azurerm.tooling]
    }
  }
  required_version = ">= 1.5.7, < 1.10.0"
}

# provider "azurerm" {
#   alias = "tooling"
#   features {}
# }
```

2024-11-12 11:42 UTC, beejjacobs requested changes
Changes look good. Once the modules change is merged we can update the tag.

2024-11-12 12:51 UTC, beejjacobs approved these changes
Looks good!

2024-11-12 13:02 UTC, merged